version: '3.8'

services:
  backend:
    container_name: actix-rust-backend
    image: actix-rust-restful:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
